[HeroIcons]
git-tree-sha1 = "b1119dbc93a42d3ffeacc38d48fbb8d6db73067c"

    [[HeroIcons.download]]
    sha256 = "cf9619993b18daa93b861b88c9c0d62914b35abab8a893c58ddc415d1b79de5e"
    url = "https://github.com/tailwindlabs/heroicons/archive/refs/tags/v2.1.5.tar.gz"
